projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: $SERVER_ENDPOINT
  prisma:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: prisma.yml
