projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: $SERVER_ENDPONT
  prisma:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: prisma/prisma.yml