version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.13
    restart: always
    ports:
    - "${PRISMA_PORT}:${PRISMA_PORT}"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        managementApiSecret: $PRISMA_MANAGEMENT_API_SECRET
        databases:
          default:
            connector: mysql
            host: mysql
            port: $MYSQL_PORT
            user: root
            password: prisma
            migrations: true
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
