version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.13
    restart: always
    ports:
      - "${PRISMA_PORT}:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        managementApiSecret: $PRISMA_MANAGEMENT_API_SECRET
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
            migrations: true

  adminer:
    image: hardware/adminer
    restart: always
    environment:
      THEME: flat
      VERSION: 4.6.2
    depends_on:
      - mysql
    ports:
      - "${ADMINER_PORT}:8888"
    volumes:
      - ./adminer.css:/adminer/adminer.css

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
volumes:
  ? mysql
