version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.15
    container_name: "${PROJECT_NAME}-prisma-server"
    restart: always
    ports:
      - "${PRISMA_PORT}:4466"
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: "${PRISMA_MANAGEMENT_API_SECRET}"
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: "${DB_USER}"
            password: "${DB_PASSWORD}"
            migrations: true

  adminer:
    image: hardware/adminer
    container_name: "${PROJECT_NAME}-adminer"
    restart: always
    ports:
      - "${ADMINER_PORT}:8888"
    volumes:
      - ./adminer.css:/adminer/adminer.css

  postgres:
    image: postgres
    container_name: "${PROJECT_NAME}-postgres-server"
    restart: always
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  ? postgres
