version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.15
    container_name: "${PROJECT_NAME}-prisma-server"
    restart: always
    ports:
      - "${PRISMA_PORT}:4466"
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: "${PRISMA_MANAGEMENT_API_SECRET}"
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: "${MYSQL_PASSWORD}"
            migrations: true
  adminer:
    image: hardware/adminer
    container_name: "${PROJECT_NAME}-adminer"
    restart: always
    depends_on:
      - mysql
    ports:
      - "${ADMINER_PORT}:8888"
    volumes:
      - ./adminer.css:/adminer/adminer.css

  mysql:
    image: mysql:5.7
    container_name: "${PROJECT_NAME}-mysql-server"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - mysql:/var/lib/mysql
    command: --disable-partition-engine-check
volumes:
  ? mysql
